#!/bin/sh /etc/rc.common

# rc.common consumes these variables.
# shellcheck disable=SC2034
START=99
STOP=10
USE_PROCD=1

PROG=/data/mihomo-router/bin/mihomo-router

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" run
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param file /etc/mihomo-router.conf
	procd_close_instance
}

stop_service() {
	"$PROG" firewall-down
}

reload_service() {
	"$PROG" update && service_stop "$PROG" && service_start "$PROG" run
}
