#!/bin/sh

output=
agent=
while [ "$#" -gt 0 ]; do
	case "$1" in
		-o) shift; output=$1 ;;
		-A) shift; agent=$1 ;;
	esac
	shift
done

[ "${MOCK_CURL_FAIL:-0}" = 0 ] || exit 22
[ -n "$output" ] || exit 2
cp "$MOCK_CURL_SOURCE" "$output"
[ -z "${MOCK_EXPECT_USER_AGENT:-}" ] || [ "$agent" = "$MOCK_EXPECT_USER_AGENT" ] || exit 2
